export const tilesUrl = [
  ['https://tile.openstreetmap.org/{z}/{x}/{y}.png', 'OpenStreetMap Carto', 'OpenStreetMap', 'https://www.openstreetmap.org/'],
  ['https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', 'MapSurfer.NET', 'GIScience Research Group @ Heidelberg University', 'http://giscience.uni-hd.de/'],
  ['https://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}', 'MapSurfer.NET Gray', 'GIScience Research Group @ Heidelberg University', 'http://giscience.uni-hd.de/'],
]
export const _tilesUrl = [
  ['https://tile.openstreetmap.org/{z}/{x}/{y}.png', 'OpenStreetMap Carto', 'OpenStreetMap', 'https://www.openstreetmap.org/'],
  ['https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', 'Humanitarian', 'Humanitarian OpenStreetMap Team', 'http://hot.openstreetmap.org/'],
  ['https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', 'MapSurfer.NET', 'GIScience Research Group @ Heidelberg University', 'http://giscience.uni-hd.de/'],
  ['https://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}', 'MapSurfer.NET Gray', 'GIScience Research Group @ Heidelberg University', 'http://giscience.uni-hd.de/'],
  ['https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png', 'OpenStreetMap.de', 'OpenStreetMap Deutschland', 'https://www.openstreetmap.de/'],
  ['https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', 'OpenStreetMap.fr', 'OpenStreetMap France', 'https://www.openstreetmap.fr/'],
  ['https://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png', 'Hydda Full', 'OpenStreetMap Sweden', 'http://openstreetmap.se/'],
  ['http://{s}.tiles.maps.sputnik.ru/{z}/{x}/{y}.png', 'Sputnik', 'Sputnik', 'https://maps.sputnik.ru/'],
  ['http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', 'CartoDB Positron', 'Carto', 'https://carto.com/attribution/'],
  ['http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', 'CartoDB Dark Matter', 'Carto', 'https://carto.com/attribution/'],
  ['http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png', 'Toner', 'Stamen Design', 'http://maps.stamen.com/'],
  ['http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg', 'Watercolor', 'Stamen Design', 'http://maps.stamen.com/'],
  ['http://{s}.tile.stamen.com/terrain/{z}/{x}/{y}.jpg', 'Terrain', 'Stamen Design', 'http://maps.stamen.com/'],
  ['http://{s}.tiles.wmflabs.org/hikebike/{z}/{x}/{y}.png', 'Hike & Bike', 'Colin Marquardt', 'http://hikebikemap.org/'],
  ['http://tileserver.memomaps.de/tilegen/{z}/{x}/{y}.png', 'ÖPNV Karte', 'ÖPNV Karte', 'https://www.öpnvkarte.de/'],
  ['https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', 'OpenTopoMap', 'OpenTopoMap', 'https://opentopomap.org/'],
  ['https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey={tfkey}', 'OpenCycleMap', 'Thunderforest', 'https://thunderforest.com/'],
  ['https://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}.png?apikey={tfkey}', 'Transport Dark', 'Thunderforest', 'https://thunderforest.com/'],
  ['https://{s}.tile.thunderforest.com/spinal-map/{z}/{x}/{y}.png?apikey={tfkey}', 'Spinal Map', 'Thunderforest', 'https://thunderforest.com/'],
  ['https://{s}.tile.thunderforest.com/pioneer/{z}/{x}/{y}.png?apikey={tfkey}', 'Pioneer', 'Thunderforest', 'https://thunderforest.com/'],
  ['https://{s}.tile.thunderforest.com/mobile-atlas/{z}/{x}/{y}.png?apikey={tfkey}', 'Mobile Atlas', 'Thunderforest', 'https://thunderforest.com/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token={mbkey}', 'Mapbox Streets', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.emerald/{z}/{x}/{y}.png?access_token={mbkey}', 'Mapbox Emerald', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.high-contrast/{z}/{x}/{y}.png?access_token={mbkey}', 'Mapbox High Contrast', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.wheatpaste/{z}/{x}/{y}.png?access_token={mbkey}', 'Wheatpaste', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.comic/{z}/{x}/{y}.png?access_token={mbkey}', 'Comic', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.pencil/{z}/{x}/{y}.png?access_token={mbkey}', 'Pencil', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
  ['https://{s}.tiles.mapbox.com/v4/mapbox.pirates/{z}/{x}/{y}.png?access_token={mbkey}', 'Pirates', 'Mapbox', 'https://www.mapbox.com/about/maps/'],
]
export const keys = {
  subdomain: '{1-4}',
  tfkey: '41f4f936f1d148f69cbd100812875c88',
  mbkey: 'pk.eyJ1IjoienZlcmlrIiwiYSI6IjVLMGxwbGsifQ.pdb83NbjTrfl9ibbdjPSsg'
}